### ISSUE TITLE
"Team-Seite" 

### ISSUE THREAD

**Issue by mirkohohmann** [technologiestiftung/citylab-microsite#27]
Mir ist gerade aufgefallen, dass die "Team"-Seite auf unserer Mainpage fehlt; nicht nur der Link sondern auch die Bilder unten 
<img width="298" alt="Bildschirmfoto 2020-05-18 um 11 46 57" src="https://user-images.githubusercontent.com/62886977/82199244-bc359f00-98fd-11ea-9e0e-5ccd97d0a002.png">

**Comment by fabianmoronzirfas** [comment]
@dnsos can you take care of this?

**Comment by dnsos** [comment]
After internal discussion, we agreed that the team section is fine in its current location (embedded in the "Über uns/About us" page) -> closing this.
