### ISSUE TITLE
Unsubscribe page broken

### ISSUE THREAD

**Issue by dnsos** [technologiestiftung/citylab-microsite#45]
Cryptic error message: `TypeError: Cannot read property '_isDestroyed' of undefined`

@fabianmoronzirfas can you please check if this problem exists for you, too? It happens when clicking the "widerrufen" in the form on the home page. Both German and English version and also on the newsletter subpage.

**Comment by fabianmoronzirfas** [comment]
talked about it. Will be done once the #43 is done.
