### ISSUE TITLE
Split content.js

### ISSUE THREAD

**Issue by jvolker** [technologiestiftung/citylab-microsite#63]
It's pretty easy to get lost in the super looooong content.js file (~ 1700 lines). I suggest to split it and create a separate file per language.

**Comment by jvolker** [comment]
Consider switching to CMS instead: #24

**Comment by fabianmoronzirfas** [comment]
Yes. CMS should be the way. For easier handling I did split the content for the smart city page into a separate file under assets/content/smartcity.js and imported it into content.js. Which works better than having everything in content.js

**Comment by Esshahn** [comment]
closing as we will not refactor the site anymore. new subpages should be handled based on the smart city procedure introduced by @fabianmoronzirfas
