### ISSUE TITLE
Mixed quotes?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/citylab-microsite#78]
Sometimes we use `""` sometimes `»«` sometimes `„“` and I've also seen `“”` I think. 

- For DE texts we should use (unten/oben) `⌥ + ^` && `⌥ + ⇧ + ^` 
- For EN texts we should use (oben/oben) `⌥ + 2` && `⌥ + ⇧ + 2`

Or we just use `»«` for all and keep it consistent. `⌥ + ⇧ + q` && `⌥ + q`

See https://www.typolexikon.de/anfuehrungszeichen/
\* All keycombos are on DE keyboard

**Comment by Esshahn** [comment]
closing. not an actual ticket and considerably low prio
